name: Trufflehog Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Run Trufflehog GitHub Action
    - name: Run Trufflehog
      uses: trufflesecurity/trufflehog@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
