name: Trufflehog Scan

on:
  push:
    branches:
      - master
      - feature/*
      - epic/*
      - fix/*
  pull_request:
    branches:
      - master

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Run Trufflehog GitHub Action
    - name: Run Trufflehog
      uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
